---

dist: focal

services:
  - docker

stages:
  - Static test
  - Build test

jobs:
  include:
    - stage: Static test
      env:
        - Test: hadolint
      language: minimal
      script:
        - docker run --rm -i -v $PWD/.hadolint.yml:/.hadolint.yml hadolint/hadolint < Dockerfile

    - stage: Static test
      env:
        - Test: dockerfile_lint
      language: node_js
      node_js:
        - "12"
      script:
        - npx --cache .npx dockerfile_lint
      cache:
        directories:
          - .npx

    - stage: Build test
      language: minimal
      before_script:
        - LATEST_AZCOPY="$(curl -sLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name' | sed 's/^v//g')"
        - test -n "$LATEST_AZCOPY"
        - export LATEST_AZCOPY
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - sudo service docker restart
        - sudo service docker status
        - docker --version
        - docker buildx version
      script:
        - docker buildx create --name samplekit
        - docker buildx use samplekit
        - docker buildx inspect --bootstrap
        - docker login -u subham328 -p Ak@sh328
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - travis_wait 30 docker buildx build --build-arg AZCOPY_VERSION="$LATEST_AZCOPY" -t subham328/docker-azcopy:$TRAVIS_COMMIT --platform linux/amd64,linux/arm64 --push . >> /dev/null 2>&1 
        - docker buildx rm samplekit
      after_success:
        - docker run --rm subham328/docker-azcopy:$TRAVIS_COMMIT azcopy --version

notifications:
  email: false
